# Generated by Django 5.2.6 on 2025-09-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_status_alter_payment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-id"]},
        ),
    ]
