# Generated by Django 5.2.6 on 2025-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[("HARD", "Hard"), ("SOFT", "Soft")],
                default="Hard",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
