# Generated by Django 5.2.6 on 2025-09-23 07:01

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_book_daily_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal(
                            "0.01000000000000000020816681711721685132943093776702880859375"
                        )
                    )
                ],
            ),
        ),
    ]
