# Generated by Django 5.2.6 on 2025-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_daily_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="astronomy/photo/"
            ),
        ),
    ]
