# Generated by Django 5.2.6 on 2025-09-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="books/photo/"
            ),
        ),
    ]
